import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: "--font-poppins",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata = {
  title: "Urban Race Developers",
  description: "Generated by create next app",
  icons: {
    icon: "/img/new-urban-fav.ico",
    shortcut: "/img/new-urban-fav.ico",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* GTM Script inside <head> if using in future */}
      </head>
      <body
        className={`${poppins.variable} antialiased`}
      >
        {/* GTM noscript immediately after <body> if using */}

        <Header />
        {children}
        <Footer />

      </body>
    </html>
  );
}